spring:
  # 공통 설정
  jpa:
    show-sql: true
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always
  # 로컬 개발 환경 (기본)
  datasource:
    url: jdbc:h2:mem:musinsadb;MODE=MySQL
    username: sa
    password:
    driver-class-name: org.h2.Driver
    generate-unique-name: false
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: alpha
    tags-sorter: alpha

  h2:
    console:
      enabled: true
      path: /h2-console
---
# 테스트 환경
spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MySQL
    username: sa
    password:
    driver-class-name: org.h2.Driver
  sql:
    init:
      mode: never
  jpa:
    defer-datasource-initialization: false
    hibernate:
      ddl-auto: create-drop # 테스트마다 DB 초기화
